name: order-service

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: orderpwd
      MYSQL_DATABASE: order
      MYSQL_PASSWORD: orderpwd
      MYSQL_USER: orderuser

