spring:
    application:
        name: order
    datasource:
        url: ${DB_URL:jdbc:mysql://localhost:3306/order}
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:orderpwd}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: ${SHOW_SQL:true}
        hibernate:
            ddl-auto: update
